/**
 * Created by jsaon on 16/7/15.
 */
import {Dimensions} from 'react-native';

let window = {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
}


let HomeDate = {
    "response": "channels",
    "isDisplay": "yes",
    "channels": [
        {
            "channelId": "1",
            "channelName": "首页"
        },
        {
            "channelId": "433c6f9289da4bb2bf7d237f735662aa",
            "channelName": "海外购"
        },
        {
            "channelId": "8168654a159149f68979efd3eb2a94c3",
            "channelName": "分享购"
        },
        {
            "channelId": "588dbe1651b24069a21aef8d220eaed5",
            "channelName": "优购直播"
        }
    ],
    "skinChannel": {},
    "module": [
        {
            "moduleTitle": "",
            "moduleStyle": "101",
            "moduleType": "3",
            "moduleWidth": "640",
            "moduleHeight": "250",
            "moduleSpace": "0",
            "modulePosition": "1",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "7864a7fa0bd24384b8871c8375a08060",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470403565581.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "7864a7fa0bd24384b8871c8375a08060",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "e7767e156179424caba972a5f3c4891b",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470389413888.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "e7767e156179424caba972a5f3c4891b",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "a2325b23f7fa484b83c3a41a61e4d602",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374538708.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "a2325b23f7fa484b83c3a41a61e4d602",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "4c4e878276b64953b7ae732ec1613e18",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470651768469.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "4c4e878276b64953b7ae732ec1613e18",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "f858531248a342c5aa8aebaa45b75284",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470376295636.jpg",
                    "detailPosition": "5",
                    "commodityName": "",
                    "commodityCode": "f858531248a342c5aa8aebaa45b75284",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "102",
            "moduleType": "2",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "2",
            "moduleTypeBg": "0",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/gmclone-3631fb1edce24760886768372aa8f4c0?requestMode=app",
                    "title": "抢红包",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406411484.png",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1001",
                    "type_argu": "782f8018c3d940138d423dcd590e988f",
                    "title": "去领券",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406424379.png",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "782f8018c3d940138d423dcd590e988f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "782f8018c3d940138d423dcd590e988f",
                    "title": "用券专区",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406539571.png",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "782f8018c3d940138d423dcd590e988f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "3b1162682a594956a9ed45d14adb0598",
                    "title": "百丽O2O",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406550354.png",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "3b1162682a594956a9ed45d14adb0598",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "102",
            "moduleType": "2",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "3",
            "moduleTypeBg": "0",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "beb6565510644e6d9bcb6c45c919a46f",
                    "title": "专业跑步",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406475423.png",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "beb6565510644e6d9bcb6c45c919a46f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "eb531927f20549c48085b13dd7b888b6",
                    "title": "篮球竞技",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406484739.png",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "eb531927f20549c48085b13dd7b888b6",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "3b27eb3118814946b710cd220f7059c4",
                    "title": "网球赛场",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406493890.png",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "3b27eb3118814946b710cd220f7059c4",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "c148f19cbeb646eaa1e12ef012a0b84e",
                    "title": "综合训练",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470406505451.png",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "c148f19cbeb646eaa1e12ef012a0b84e",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "104",
            "moduleType": "4",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "4",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/gmclone-3631fb1edce24760886768372aa8f4c0?requestMode=app",
                    "title": "金牌运动周劲爆开幕,百万卡券等你来领~",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374910556.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "18",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "5",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "d25eb525e27241cfb578db3b43a65877",
            "secKillImg": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470621257094.png",
            "secKillState": "1",
            "secKillLeftTime": "25943",
            "secKillStartTime": "2016-08-10 18:00:00",
            "moduleDetail": [
                {
                    "type": "1027",
                    "type_argu": "100386532",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/adidasclassic/2016/100386532/100386532_01_s.jpg?2",
                    "detailPosition": "1",
                    "commodityName": "adidas阿迪三叶草2016年新款女子三叶草系列休闲鞋S78963",
                    "commodityCode": "100386532",
                    "secSkillStat": "0",
                    "secSkillPrice": "398",
                    "publicPrice": "829",
                    "salePrice": "398"
                },
                {
                    "type": "1027",
                    "type_argu": "100382380",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/teenmix/2016/100382380/100382380_01_s.jpg?4",
                    "detailPosition": "2",
                    "commodityName": "Teenmix/天美意2016夏金/银色PU女鞋31750BT6",
                    "commodityCode": "100382380",
                    "secSkillStat": "0",
                    "secSkillPrice": "188",
                    "publicPrice": "698",
                    "salePrice": "188"
                },
                {
                    "type": "1027",
                    "type_argu": "100440344",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/paulfrank/2016/100440344/100440344_01_s.jpg?2",
                    "detailPosition": "3",
                    "commodityName": "Paul Frank大嘴猴2016新款男子短袖针织衫PFATE162759M76",
                    "commodityCode": "100440344",
                    "secSkillStat": "0",
                    "secSkillPrice": "129",
                    "publicPrice": "369",
                    "salePrice": "129"
                },
                {
                    "type": "1027",
                    "type_argu": "100457440",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/nike/2016/100457440/100457440_01_s.jpg?2",
                    "detailPosition": "4",
                    "commodityName": "NIKE耐克2016年新款男子AS NIKE TEE-SOLSTICE JDIT恤810371-455",
                    "commodityCode": "100457440",
                    "secSkillStat": "0",
                    "secSkillPrice": "139",
                    "publicPrice": "229",
                    "salePrice": "139"
                },
                {
                    "type": "1027",
                    "type_argu": "100440343",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/paulfrank/2016/100440343/100440343_01_s.jpg?2",
                    "detailPosition": "5",
                    "commodityName": "Paul Frank大嘴猴2016新款男子短袖针织衫PFATE162759M31",
                    "commodityCode": "100440343",
                    "secSkillStat": "0",
                    "secSkillPrice": "129",
                    "publicPrice": "369",
                    "salePrice": "129"
                },
                {
                    "type": "1027",
                    "type_argu": "100430788",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/nike/2016/100430788/100430788_01_s.jpg?2",
                    "detailPosition": "6",
                    "commodityName": "NIKE耐克2016年新款女子AS NIKE TEE-BF LYNX JDIT恤779264-063",
                    "commodityCode": "100430788",
                    "secSkillStat": "0",
                    "secSkillPrice": "110",
                    "publicPrice": "229",
                    "salePrice": "110"
                },
                {
                    "type": "1027",
                    "type_argu": "100441126",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/paulfrank/2016/100441126/100441126_01_s.jpg?2",
                    "detailPosition": "7",
                    "commodityName": "Paul Frank大嘴猴2016新款男子短袖针织衫PFATE162759M13",
                    "commodityCode": "100441126",
                    "secSkillStat": "0",
                    "secSkillPrice": "129",
                    "publicPrice": "369",
                    "salePrice": "129"
                },
                {
                    "type": "1027",
                    "type_argu": "100432025",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/adidasneo/2016/100432025/100432025_01_s.jpg?2",
                    "detailPosition": "8",
                    "commodityName": "adidas阿迪休闲2016年新款女子休闲生活系列T恤AJ8639",
                    "commodityCode": "100432025",
                    "secSkillStat": "1",
                    "secSkillPrice": "115",
                    "publicPrice": "229",
                    "salePrice": "115"
                },
                {
                    "type": "1027",
                    "type_argu": "100408002",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/adidas/2016/100408002/100408002_01_s.jpg?2",
                    "detailPosition": "9",
                    "commodityName": "adidas阿迪达斯2016年新款女子运动休闲系列T恤AI6145",
                    "commodityCode": "100408002",
                    "secSkillStat": "1",
                    "secSkillPrice": "108",
                    "publicPrice": "229",
                    "salePrice": "108"
                },
                {
                    "type": "1027",
                    "type_argu": "100264462",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/chums/2015/100264462/100264462_01_s.jpg?2",
                    "detailPosition": "10",
                    "commodityName": "CHUMS洽睦斯 专柜同款 女子 棉X竹纤维短袖T裇CH11-1016-W001",
                    "commodityCode": "100264462",
                    "secSkillStat": "1",
                    "secSkillPrice": "159",
                    "publicPrice": "368",
                    "salePrice": "159"
                },
                {
                    "type": "1027",
                    "type_argu": "100370297",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/adidasclassic/2016/100370297/100370297_01_s.jpg?2",
                    "detailPosition": "11",
                    "commodityName": "adidas阿迪三叶草2016新款男子三叶草系列休闲鞋F37493",
                    "commodityCode": "100370297",
                    "secSkillStat": "1",
                    "secSkillPrice": "398",
                    "publicPrice": "799",
                    "salePrice": "398"
                },
                {
                    "type": "1027",
                    "type_argu": "100470019",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/puma/2016/100470019/100470019_01_s.jpg?3",
                    "detailPosition": "12",
                    "commodityName": "PUMA彪马2016新款男童基础系列Sesame Street Tee短袖T恤83881702",
                    "commodityCode": "100470019",
                    "secSkillStat": "1",
                    "secSkillPrice": "109",
                    "publicPrice": "199",
                    "salePrice": "109"
                },
                {
                    "type": "1027",
                    "type_argu": "100417613",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/adidasneo/2016/100417613/100417613_01_s.jpg?2",
                    "detailPosition": "13",
                    "commodityName": "adidas阿迪休闲2016年新款男子休闲生活系列T恤AK1006",
                    "commodityCode": "100417613",
                    "secSkillStat": "1",
                    "secSkillPrice": "115",
                    "publicPrice": "229",
                    "salePrice": "115"
                },
                {
                    "type": "1027",
                    "type_argu": "100447994",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i2.ygimg.cn/pics/belle/2016/100447994/100447994_01_s.jpg?4",
                    "detailPosition": "14",
                    "commodityName": "Belle/百丽2016春季红色羊皮休闲平跟浅口女单鞋688-8AQ6",
                    "commodityCode": "100447994",
                    "secSkillStat": "1",
                    "secSkillPrice": "238",
                    "publicPrice": "838",
                    "salePrice": "238"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "6",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374978996.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "183",
            "moduleSpace": "0",
            "modulePosition": "7",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/gmclone-3631fb1edce24760886768372aa8f4c0?requestMode=app",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470620728938.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "4",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "10",
            "modulePosition": "8",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "ae9d9c258bec41f9be1e7da1a961d67d",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470794068964.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "ae9d9c258bec41f9be1e7da1a961d67d",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "7a5205573d1a4fb3ac62b0d6fe8b50e6",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470622389325.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "7a5205573d1a4fb3ac62b0d6fe8b50e6",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "f9f48e4cd3634e0b9e6b5e92d8945a48",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470378438086.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "f9f48e4cd3634e0b9e6b5e92d8945a48",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "9",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470299769478.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "10",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "81e7187543e14cea96feaedc68965434",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470404959493.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "81e7187543e14cea96feaedc68965434",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "11",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "dd6003d892094cf4b2f997d812fa9222",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470403411982.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "dd6003d892094cf4b2f997d812fa9222",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "55bf18a6bf874e138f943cdc4b0d8b39",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470403420442.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "55bf18a6bf874e138f943cdc4b0d8b39",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "0016223fba784fc6bde84fc4a78058c7",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470403428842.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "0016223fba784fc6bde84fc4a78058c7",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "12",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470299850968.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "220",
            "moduleSpace": "0",
            "modulePosition": "13",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "3b1162682a594956a9ed45d14adb0598",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470380809273.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "3b1162682a594956a9ed45d14adb0598",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "250",
            "moduleSpace": "10",
            "modulePosition": "14",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "5791192d97ca4cb6b6f5e993813a3f21",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470726972932.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "5791192d97ca4cb6b6f5e993813a3f21",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "15",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "af346e66faba4f9eaf874e8ee896d22c",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470375328993.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "af346e66faba4f9eaf874e8ee896d22c",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "1026",
                    "type_argu": "36eea1e21fc042b0b0f59c82b1e52373",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470375391112.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "36eea1e21fc042b0b0f59c82b1e52373",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "5a6c324b5fc347b286082743087136d1",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470375401532.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "5a6c324b5fc347b286082743087136d1",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "16",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470299364681.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "17",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "64b235398e3442d8b215dd311c838ded",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374044851.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "64b235398e3442d8b215dd311c838ded",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "18",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "20d57a5472d8495b85bea03c366178cd",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374085211.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "20d57a5472d8495b85bea03c366178cd",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "a7ecd39d51594185881ca79c2422e6a6",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374116601.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "a7ecd39d51594185881ca79c2422e6a6",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "6ddeaed898f849c09acf1eb2d1a4073c",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374129071.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "6ddeaed898f849c09acf1eb2d1a4073c",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "19",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470299440640.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "20",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "01e6b838805c4a70be768666e3ffe46f",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470376251946.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "01e6b838805c4a70be768666e3ffe46f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "21",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "b8578472fb8d4c359bb383791045f29e",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470358885887.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "b8578472fb8d4c359bb383791045f29e",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "9ae7b2c91e424386914495f77f14a103",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470358890718.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "9ae7b2c91e424386914495f77f14a103",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "47de0e18ab2148359087d6880078892b",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470358895758.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "47de0e18ab2148359087d6880078892b",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "22",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470299023843.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "23",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "a6b1a88f4c614f099042a259d92c2048",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374241040.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "a6b1a88f4c614f099042a259d92c2048",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "24",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "1b0bf498d4404206abc70999f19320be",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470374267270.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "1b0bf498d4404206abc70999f19320be",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "4c63a6186b344f0bb617716a33e13159",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470623528539.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "4c63a6186b344f0bb617716a33e13159",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "ae9d9c258bec41f9be1e7da1a961d67d",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470623538739.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "ae9d9c258bec41f9be1e7da1a961d67d",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "25",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470298865754.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "26",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "412bf431ae894a31aeec1b528ea1438f",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470291205115.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "412bf431ae894a31aeec1b528ea1438f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "1",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "27",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "ae7166d9d25041dc8ec9d143bafade22",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470292079259.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "ae7166d9d25041dc8ec9d143bafade22",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "5df396da8e71433e976a805cbee07cc5",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470303155636.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "5df396da8e71433e976a805cbee07cc5",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "7d33744123114e4996496c059495ae32",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470303158375.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "7d33744123114e4996496c059495ae32",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "28",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468201470474.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "246",
            "moduleSpace": "0",
            "modulePosition": "29",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "e34e35063b6c42aa95cb7529e7590d2d",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470661189874.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "e34e35063b6c42aa95cb7529e7590d2d",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "10",
            "modulePosition": "30",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "00911a3ccd3d42fd895311b38e972b97",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205079082.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "00911a3ccd3d42fd895311b38e972b97",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "cd1f13d3751d442cb2aab9cedcc55165",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205095942.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "cd1f13d3751d442cb2aab9cedcc55165",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "17e8b6036ba845199b44ebf6dc7eefb5",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205108041.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "17e8b6036ba845199b44ebf6dc7eefb5",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "f5f4eda3ffd7463e8f5f28e796a98e74",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205125712.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "f5f4eda3ffd7463e8f5f28e796a98e74",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "31",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "a2ae5e426dbc43b8908458211096f5c3",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205202501.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "a2ae5e426dbc43b8908458211096f5c3",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "4d127c47ace2419399317a798a9cd1b3",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205232861.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "4d127c47ace2419399317a798a9cd1b3",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "c18c8df37518416dac4b58f348aeedd9",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205248291.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "c18c8df37518416dac4b58f348aeedd9",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "323bdf395223433daf298adb78a3362d",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468205271651.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "323bdf395223433daf298adb78a3362d",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "32",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468201511954.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "8",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "33",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/adidas-brand?requestMode=app",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468230601575.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/nike-brand?requestMode=app",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468230610805.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "34",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/adidasneo-brand?requestMode=app",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468230719622.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "13",
                    "type_argu": "http://m.yougou.com/puma-brand?requestMode=app",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468230752868.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "0b7e1edd162b45fd8610f633ef8e2d7f",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744460775.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "0b7e1edd162b45fd8610f633ef8e2d7f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "26b62da462ef4c9b9293dfb1e8fdd5df",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744465465.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "26b62da462ef4c9b9293dfb1e8fdd5df",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "35",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "b65e546a86a84a53b5393ee6c3bc97a0",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744485039.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "b65e546a86a84a53b5393ee6c3bc97a0",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "23808871e17c4021ae4cea9f44607381",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744490363.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "23808871e17c4021ae4cea9f44607381",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "dca38398893141618070636eae0d67f4",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744494825.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "dca38398893141618070636eae0d67f4",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "25da3263ac3b48daac52355083db787f",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/06/1464744503673.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "25da3263ac3b48daac52355083db787f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "50",
            "moduleSpace": "0",
            "modulePosition": "36",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "0",
                    "type_argu": "",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1468201561884.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "37",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "671313a206dd4666938e8e61b2e5191b",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574175657.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "671313a206dd4666938e8e61b2e5191b",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "3b95bf0e824e4552bca3190d66848443",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574210047.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "3b95bf0e824e4552bca3190d66848443",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "b0fba84233f44964960033aad1f9a8ea",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574256505.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "b0fba84233f44964960033aad1f9a8ea",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "6d3de0795cfc4b9e9e1fe2cbd1246746",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574283195.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "6d3de0795cfc4b9e9e1fe2cbd1246746",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "38",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "00336fa071284f968d825820a80e83d9",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574256207.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "00336fa071284f968d825820a80e83d9",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "42aeca2a6b08467abed191d400ffde47",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574296097.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "42aeca2a6b08467abed191d400ffde47",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "4f6c81f662e148348f2b4e28e323a82b",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574317465.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "4f6c81f662e148348f2b4e28e323a82b",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "0ca068c62719437d8ad9ff06ca6494b4",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574335481.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "0ca068c62719437d8ad9ff06ca6494b4",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "10",
            "moduleType": "1",
            "moduleWidth": "0",
            "moduleHeight": "0",
            "moduleSpace": "0",
            "modulePosition": "39",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "5",
                    "type_argu": "7338d4c4f0f84596bb9115fda0926632",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574403633.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "7338d4c4f0f84596bb9115fda0926632",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "8476c02df0344d03bcceb3d37e546eda",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574407327.jpg",
                    "detailPosition": "2",
                    "commodityName": "",
                    "commodityCode": "8476c02df0344d03bcceb3d37e546eda",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "9fd7da561c35432486d3f500539028bb",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/07/1469166209470.jpg",
                    "detailPosition": "3",
                    "commodityName": "",
                    "commodityCode": "9fd7da561c35432486d3f500539028bb",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                },
                {
                    "type": "5",
                    "type_argu": "2ccbe6cd65ef4eb48706721ebd80b5eb",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/05/1464574416984.jpg",
                    "detailPosition": "4",
                    "commodityName": "",
                    "commodityCode": "2ccbe6cd65ef4eb48706721ebd80b5eb",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        },
        {
            "moduleTitle": "",
            "moduleStyle": "11",
            "moduleType": "1",
            "moduleWidth": "620",
            "moduleHeight": "200",
            "moduleSpace": "10",
            "modulePosition": "40",
            "moduleTypeBg": "1",
            "moduleBg": "",
            "secKillId": "",
            "secKillImg": "",
            "secKillState": "0",
            "secKillLeftTime": "0",
            "secKillStartTime": "",
            "moduleDetail": [
                {
                    "type": "1026",
                    "type_argu": "782f8018c3d940138d423dcd590e988f",
                    "title": "",
                    "subtitle": "",
                    "image": "http://i1.ygimg.cn/pics/mobile/homepage/2016/08/1470639468736.jpg",
                    "detailPosition": "1",
                    "commodityName": "",
                    "commodityCode": "782f8018c3d940138d423dcd590e988f",
                    "secSkillStat": "0",
                    "secSkillPrice": "0",
                    "publicPrice": "0",
                    "salePrice": "0"
                }
            ]
        }
    ]
}


export default {
    window: window,
    HomeDate:HomeDate,
}