/**
 * Created by jason  on 16/7/14.
 * action类型
 */
//主页actions
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST';
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST';

export const FETCH_SEAUGO_LIST = 'FETCH_SEAUGO_LIST';
export const RECEIVE_SEAUGO_LIST = 'RECEIVE_SEAUGO_LIST';

//牌子页actions

export const FETCH_BRAND_LIST = 'FETCH_BRAND_LIST';
export const RECEIVE_BRAND_LIST = 'RECEIVE_BRAND_LIST';


export const FETCH_SHOPCART_LIST = 'FETCH_SHOPCART_LIST';
export const RECEIVE_SHOPCART_LIST = 'RECEIVE_SHOPCART_LIST';

export const FETCH_SELECTAll_LIST = 'FETCH_SELECTAll_LIST';
export const SELECTAll_SHOPCART_LIST = 'SELECTAll_SHOPCART_LIST';

export const FETCH_SELECTONE_LIST = 'FETCH_SELECTONE_LIST';
export const SELECTONE_SHOPCART_LIST = 'SELECTONE_SHOPCART_LIST';



