/**
 * Created by jason  on 16/7/14.
 * action类型
 */
//主页actions
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST';
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST';

export const FETCH_SEAUGO_LIST = 'FETCH_SEAUGO_LIST';
export const RECEIVE_SEAUGO_LIST = 'RECEIVE_SEAUGO_LIST';

//牌子页actions

export const FETCH_BRAND_LIST = 'FETCH_BRAND_LIST';
export const RECEIVE_BRAND_LIST = 'RECEIVE_BRAND_LIST';


export const FETCH_BRANDDETAIL_LIST = 'FETCH_BRANDDETAIL_LIST';
export const RECEIVE_BRANDDETAIL_LIST = 'RECEIVE_BRANDDETAIL_LIST';
